### ISSUE TITLE
Derive folder structure from properties

### ISSUE THREAD

**Issue by ycnmhd** [gr0grig/obsidian-virt-folder#3]
Thank you for this plugin.

I have an idea, but i'm not sure if it is compatible with your vision.
When implemented, the folder structure would be derived from YAML properties.
The user would define multiple `derived paths` such as `[genre]/[decade]/[year]` and `[genre]/[author]` and would be able to quickly switch between them.
If the YAML property is an array, there would be N virtual folders

**Comment by gr0grig** [comment]
Hi. This is an interesting idea, but I don't understand yet how it is better. The option you proposed has a right to exist, but it is a different plugin structure. Now each virtual folder should be a real existing note. When searching for a note via the command, the full path is already displayed. I was thinking about including the full path in the search, and not just the note name.

**Comment by johnfuller** [comment]
I don't see how this is an improvement, because you can already do this by setting the parents. Make the parent a year or author note. Then you can change the structure by changing the categorization note.

It also changes the nature of the plugin. The plugin is meant to display a hierarchy of linked notes. I love this functionality because Obsidian has no great method of visualization of linked notes. I find the graph view to be lacking.

If you want to display a hierarchy, there's likely other add-ons which handle this.
